services:
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        volumes:
            - ./data:/data
        # persistent data to disk
        command: redis-server --appendonly yes